### ISSUE TITLE
Stopping docker container exceeds grace period

### ISSUE THREAD

**Issue by wvffle** [Sorunome/mx-puppet-bridge#57]
When I stop my docker container discord, steam and slack (basically all of mx-puppet-bridge based) bridges are exceeding the grace period defined in the docker-compose.yml every single time. 

Setting the `stop_grace_period` to a low value does not satisfy me as those bridges are clearly not shutting down correctly. 
Logs do not contain any errors so probably the node server does not receive the SIGTERM

I have following docker-compose.yml:
```yml
version: '2.4'
services:
  discord:
    build: https://github.com/matrix-discord/mx-puppet-discord.git
    restart: always
    stop_grace_period: 2m
    volumes:
      - /opt/mx-puppet-discord:/data
    ports:
      - 8434:8434
```
